-- Crear tabla de usuarios
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) UNIQUE NOT NULL,
    contrasena VARCHAR2(100) NOT NULL,
    rol VARCHAR2(20) CHECK (rol IN ('administrador', 'profesor')) NOT NULL
);

-- Crear tabla de préstamos
CREATE TABLE prestamos (
    id_prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sala VARCHAR2(50) NOT NULL,
    hora_reserva VARCHAR2(10) NOT NULL,
    fecha_reserva DATE NOT NULL,
    observaciones VARCHAR2(500),
    id_usuario NUMBER,
    CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);